---
- name: ensure prometheus.yml
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_conf_file }}"
    owner: root
    group: root
    mode: 0644
  become: true
  register: prometheus_conf
